# Generated by Django 3.2.9 on 2021-11-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnvisaNome',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(db_column='nomeProduto', max_length=250)),
            ],
            options={
                'db_table': 'anvisa_nome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnvisaPrincipioativo',
            fields=[
                ('id_pativo', models.IntegerField(db_column='id_pAtivo', primary_key=True, serialize=False)),
                ('nome_pativo', models.CharField(db_column='nome_pAtivo', max_length=250)),
                ('translated_pativo', models.CharField(db_column='translated_pAtivo', max_length=250)),
            ],
            options={
                'db_table': 'anvisa_principioativo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BigtableNomes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_principal', models.IntegerField()),
                ('nome', models.CharField(max_length=250)),
                ('tipo_origem', models.IntegerField()),
            ],
            options={
                'db_table': 'bigtable_nomes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DrugbankNome',
            fields=[
                ('drugbank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'drugbank_nome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnvisaNomePrincipioativo',
            fields=[
                ('idproduto', models.OneToOneField(db_column='idProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_interacao_medicamentos.anvisanome')),
            ],
            options={
                'db_table': 'anvisa_nome_principioativo',
                'managed': False,
            },
        ),
    ]
