# Generated by Django 3.2.9 on 2021-11-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_interacao_medicamentos', '0002_auto_20211107_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='anvisanomeprincipioativo',
            name='idprincipio',
            field=models.ForeignKey(db_column='idPrincipio', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app_interacao_medicamentos.anvisaprincipioativo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='anvisanomeprincipioativo',
            unique_together={('idproduto', 'idprincipio')},
        ),
        migrations.CreateModel(
            name='TesteInteracao',
            fields=[
                ('item_1', models.IntegerField(primary_key=True, serialize=False)),
                ('item_2', models.IntegerField()),
            ],
            options={
                'db_table': 'teste_interacao',
                'managed': True,
                'unique_together': {('item_1', 'item_2')},
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbank_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugbank_id1', to='app_interacao_medicamentos.drugbankanvisa')),
                ('drugbank_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugbank_id2', to='app_interacao_medicamentos.drugbankanvisa')),
            ],
        ),
    ]
