# Generated by Django 3.2.9 on 2021-11-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_interacao_medicamentos', '0003_auto_20211115_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugbankInteracao',
            fields=[
                ('drugbank_id1', models.OneToOneField(db_column='drugbank_id1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='drugbank_id1', serialize=False, to='app_interacao_medicamentos.drugbanknome')),
            ],
            options={
                'db_table': 'drugbank_interacao',
                'managed': False,
            },
        ),
    ]
